"use strict";

sh.primitive_tiles = {
	'.' : 'background',
	'1' : ['lava1', 'lava3'],
	'2' : ['lava2', 'lava4'],
	'a' : 'rock1',
	'b' : 'rock2',
	'c' : 'rock3',
	'd' : 'rock4'
}

sh.action_tiles = {
	'1' : function(){ sh.increaseCounter(sh.lava_heat_value); },
	'2' : function(){ sh.increaseCounter(sh.lava_heat_value); }
}

sh.random_tiles = {
	'L' : ['1', '2'],
	'R' : ['a', 'b', 'c', 'd']
}

sh.leveldata = [
["RRRRRRRRRR", function(){sh.evt(sh.winGameEvent);}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createBoss();}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.evt(sh.scrollSpeedInterpolateEvent(0, 2*60));}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createHorizontalTurret(true);}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RLLLRRRRRR", function(){}],
["RLLRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createHorizontalTurret(false);}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.evt(sh.scrollSpeedInterpolateEvent(1, 120));}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createBigTowerEnemy(200);}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createTowerEnemy(100);}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.evt(sh.scrollSpeedInterpolateEvent(0.5, 120));}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createSpreadShooterEnemy();}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRLRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRLRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RLLRRRLRRR", function(){}],
["RLRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createBoringEnemy();}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createBoringEnemy();}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){sh.createBoringEnemy();}],
["RRRLRRRRRR", function(){}],
["RRLLLRRRRR", function(){}],
["LLLLLLLLLL", function(){}],
["RLLLRLLRLL", function(){}],
["RLLRRRLRRR", function(){}],
["RRRRRRRRRR", function(){}],
["RRRRRRRRRR", function(){}],
[".RRRR.RRR.", function(){}],
["...R......", function(){}],
["..........", function(){}],
["..........", function(){}],
["..........", function(){}],
["..........", function(){}],
["..........", function(){}],
["..........", function(){sh.createBlinkingText(4, "Blinkage", 130, 75, 20, "rgb(255, 255, 255)","Italic 16pt Impact");}],
["..........", function(){sh.evt(sh.showTextEvent("With font", 140, 125, 120, "rgb(255, 255, 255)","20pt Impact"));}],
["..........", function(){sh.evt(sh.showTextEvent("With color", 50, 100, 120, "rgb(255, 0, 255)"));}],
["..........", function(){sh.evt(sh.showTextEvent("With 2x lifetime", 50, 150, 120));}],
["..........", function(){sh.evt(sh.showTextEvent("Plain text event", 50, 200));}],
["..........", function(){}]
];
